name = "JWTs"
uuid = "d850fbd6-035d-5a70-a269-1ca2e636ac6c"
keywords = ["julialang", "jwt", "jwt-authentication", "jwkset", "signing"]
license = "MIT"
desc = "JSON Web Tokens (JWT) for Julia"
authors = ["Tanmay Mohapatra <tanmaykm@gmail.com>", "contributors: https://github.com/JuliaWeb/JWTs.jl/graphs/contributors"]
version = "0.3.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
MbedTLS = "739be429-bea8-5141-9913-cc70e7f3736d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Downloads = "1"
JSON = "0.20, 0.21"
MbedTLS = "0.6.8, 0.7, 1"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
